fastlane_version "2.102.0"

default_platform :ios

platform :android do
  before_all do
    apk = "feed-the-monster.apk"

    ENV["FL_HOCKEY_APK"] = apk
	ENV["FL_HOCKEY_API_TOKEN"] = "834d997e517543058d09e13402fc5410"

	ENV["FL_SLACK_CHANNEL"] = "#build"
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"

    ENV["SUPPLY_APK"] = apk
  end

  desc "Deploy Feed the Monster Live to alpha track on Google Play"

  lane :beta do
    hockey(
      public_identifier:"10d447ce2a1b40cc80a17676187e73e0",
      timeout: 3600,
      bypass_cdn: true
    )

    supply(
      apk: "feed-the-monster.apk",
      json_key: "/Users/administrator/fastlane_google_upload_key.json",
      package_name: "com.eduapp4syria.feedthemonster",
      track: "alpha"
    )

    slack(
      message: "Deployed Feed the Monster Google Live to alpha track on Google Play.",
      success: true
    )
  end

  error do |lane, exception|
    slack(
      channel: "#build",
      message: exception.message,
      success: false
    )
  end  
end